//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Input/Gameplay.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/Gameplay.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Gameplay: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Gameplay()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Gameplay"",
    ""maps"": [
        {
            ""name"": ""gates"",
            ""id"": ""2350a59e-ec27-4434-bcdb-7597a484e1c2"",
            ""actions"": [
                {
                    ""name"": ""StretchingZ"",
                    ""type"": ""Value"",
                    ""id"": ""5cae4b11-519e-474e-8ee2-faf8b9f2df10"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StretchingX"",
                    ""type"": ""Value"",
                    ""id"": ""252294f3-6ca6-415a-a14d-b3cd19589922"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StretchingSpace"",
                    ""type"": ""Value"",
                    ""id"": ""94872567-cbf9-47df-adea-6d7d6b71ab2f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""531a59d3-d3ad-4b36-99d8-b8ab0ce29c76"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1ee799ab-dad0-43d1-8c04-3b3d07e324ef"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StretchingZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86d030be-fbd5-43db-91c7-b9560aa3ed40"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StretchingX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a962415-3115-4688-8013-57460b4bc4e0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StretchingSpace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4341b86-b834-49c6-8e72-71176219e71d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // gates
        m_gates = asset.FindActionMap("gates", throwIfNotFound: true);
        m_gates_StretchingZ = m_gates.FindAction("StretchingZ", throwIfNotFound: true);
        m_gates_StretchingX = m_gates.FindAction("StretchingX", throwIfNotFound: true);
        m_gates_StretchingSpace = m_gates.FindAction("StretchingSpace", throwIfNotFound: true);
        m_gates_Restart = m_gates.FindAction("Restart", throwIfNotFound: true);
    }

    ~@Gameplay()
    {
        UnityEngine.Debug.Assert(!m_gates.enabled, "This will cause a leak and performance issues, Gameplay.gates.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // gates
    private readonly InputActionMap m_gates;
    private List<IGatesActions> m_GatesActionsCallbackInterfaces = new List<IGatesActions>();
    private readonly InputAction m_gates_StretchingZ;
    private readonly InputAction m_gates_StretchingX;
    private readonly InputAction m_gates_StretchingSpace;
    private readonly InputAction m_gates_Restart;
    /// <summary>
    /// Provides access to input actions defined in input action map "gates".
    /// </summary>
    public struct GatesActions
    {
        private @Gameplay m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GatesActions(@Gameplay wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "gates/StretchingZ".
        /// </summary>
        public InputAction @StretchingZ => m_Wrapper.m_gates_StretchingZ;
        /// <summary>
        /// Provides access to the underlying input action "gates/StretchingX".
        /// </summary>
        public InputAction @StretchingX => m_Wrapper.m_gates_StretchingX;
        /// <summary>
        /// Provides access to the underlying input action "gates/StretchingSpace".
        /// </summary>
        public InputAction @StretchingSpace => m_Wrapper.m_gates_StretchingSpace;
        /// <summary>
        /// Provides access to the underlying input action "gates/Restart".
        /// </summary>
        public InputAction @Restart => m_Wrapper.m_gates_Restart;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_gates; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GatesActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GatesActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GatesActions" />
        public void AddCallbacks(IGatesActions instance)
        {
            if (instance == null || m_Wrapper.m_GatesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GatesActionsCallbackInterfaces.Add(instance);
            @StretchingZ.started += instance.OnStretchingZ;
            @StretchingZ.performed += instance.OnStretchingZ;
            @StretchingZ.canceled += instance.OnStretchingZ;
            @StretchingX.started += instance.OnStretchingX;
            @StretchingX.performed += instance.OnStretchingX;
            @StretchingX.canceled += instance.OnStretchingX;
            @StretchingSpace.started += instance.OnStretchingSpace;
            @StretchingSpace.performed += instance.OnStretchingSpace;
            @StretchingSpace.canceled += instance.OnStretchingSpace;
            @Restart.started += instance.OnRestart;
            @Restart.performed += instance.OnRestart;
            @Restart.canceled += instance.OnRestart;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GatesActions" />
        private void UnregisterCallbacks(IGatesActions instance)
        {
            @StretchingZ.started -= instance.OnStretchingZ;
            @StretchingZ.performed -= instance.OnStretchingZ;
            @StretchingZ.canceled -= instance.OnStretchingZ;
            @StretchingX.started -= instance.OnStretchingX;
            @StretchingX.performed -= instance.OnStretchingX;
            @StretchingX.canceled -= instance.OnStretchingX;
            @StretchingSpace.started -= instance.OnStretchingSpace;
            @StretchingSpace.performed -= instance.OnStretchingSpace;
            @StretchingSpace.canceled -= instance.OnStretchingSpace;
            @Restart.started -= instance.OnRestart;
            @Restart.performed -= instance.OnRestart;
            @Restart.canceled -= instance.OnRestart;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GatesActions.UnregisterCallbacks(IGatesActions)" />.
        /// </summary>
        /// <seealso cref="GatesActions.UnregisterCallbacks(IGatesActions)" />
        public void RemoveCallbacks(IGatesActions instance)
        {
            if (m_Wrapper.m_GatesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GatesActions.AddCallbacks(IGatesActions)" />
        /// <seealso cref="GatesActions.RemoveCallbacks(IGatesActions)" />
        /// <seealso cref="GatesActions.UnregisterCallbacks(IGatesActions)" />
        public void SetCallbacks(IGatesActions instance)
        {
            foreach (var item in m_Wrapper.m_GatesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GatesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GatesActions" /> instance referencing this action map.
    /// </summary>
    public GatesActions @gates => new GatesActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "gates" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GatesActions.AddCallbacks(IGatesActions)" />
    /// <seealso cref="GatesActions.RemoveCallbacks(IGatesActions)" />
    public interface IGatesActions
    {
        /// <summary>
        /// Method invoked when associated input action "StretchingZ" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStretchingZ(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "StretchingX" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStretchingX(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "StretchingSpace" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStretchingSpace(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Restart" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRestart(InputAction.CallbackContext context);
    }
}
